#!/usr/bin/env bash

echo "Creating local tmp folder, (for vim swap file) ..."
  mkdir ~/tmp

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing tig plugin for GIT, a good show commits history tools ..."
  brew install tig

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing IRSSI, nice terminal IRC client ..."
  brew install irssi

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install mysql

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python

echo "Installing Redis, a good key-value database ..."
  brew install redis

# echo "Installing tmux, a good way to save project state and switch between projects ..."
#   brew install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

# bash < <(curl -s https://raw.github.com/jagg81/laptop/custom/master/ruby)
# bash < <(curl -s https://raw.github.com/jagg81/laptop/custom/master/heroku)
